#### Importing numpy package

In [1]:
import numpy as np

#### Printing version and configuration

In [2]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mani/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/mani/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mani/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

#### Create a nullvector of size 10

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create a null vector of size 10 and make the 5th element to 1

In [4]:
a1 = np.zeros(10)
a1[4] = 1
a1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Creating a numpy array with values ranging from 10 to 49

In [5]:
a2 = np.arange(10, 50)
a2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Reversing a numpy array

In [6]:
a2[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Creating a 3 *3 numpy array with values ranging from 0 to 9

In [7]:
a3 = np.arange((9)).reshape(3,3)
a3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Finding the indices of nonzero elements

In [8]:
a4 = np.nonzero([1, 2, 4, 8, 0])
a4

(array([0, 1, 2, 3], dtype=int64),)

#### Creating a 3*3 identity matrix

In [9]:
a5 = np.eye(3)
a5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Creating a 3*3*3 matrix with random values

In [10]:
a6 = np.random.random((3, 3, 3))
a6

array([[[0.82549421, 0.97200575, 0.94528341],
        [0.26022652, 0.66565516, 0.4314622 ],
        [0.20777852, 0.16894071, 0.96358406]],

       [[0.24466568, 0.78530954, 0.91753602],
        [0.60504013, 0.3383271 , 0.0039517 ],
        [0.87105363, 0.67308814, 0.98968995]],

       [[0.26236027, 0.61519973, 0.25512572],
        [0.01984022, 0.19743714, 0.56900711],
        [0.088831  , 0.38024968, 0.74858764]]])

#### Creating a 10*10 array and finding min, max elements

In [11]:
a7 = np.random.random((10,10))
a7min, a7max = a7.min(), a7.max()
print(a7min, a7max)

0.002975178124750566 0.9995510280002822


#### Creating a random vector of size 30 and finding the mean

In [12]:
a8 = np.arange(30)
print(a8.mean())

14.5


#### Create a 2D array with 0 on border and 1 inside

In [13]:
a9 = np.zeros((10, 10))
a9[1:-1, 1:-1]=1
a9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Create a 2D array with 1's and 1 on border and o inside

In [14]:
a = np.ones((10, 10))
a[1:-1, 1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Create a 2D array of one's and border with 0

In [15]:
a = np.ones((10, 10))
a[0:, 0::len(a)-1]=0
a[0::len(a)-1 ]=0
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Check the output of following

In [16]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
0.3 == 3 * 0.1)

nan False False nan False


#### Create a 5*5 matrix with values 1, 2, 3, 4 just below the diagonal

In [17]:
a = np.diag(1+np.arange(4), k= -1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Create a checkboard pattern of 8*8 matrix

In [18]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### Creating  a checkboard of 8* 8 using tile function 

In [19]:
a = np.tile( np.array([[0,1],[1,0]]), (4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### Multiplying a 5* 3 matrix with 3* 2 matrix

In [20]:
a = np.dot(np.ones((5, 3)), np.ones((3, 2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### Given a 1D array, negate all the elements between 3 and 8

In [21]:
a = np.arange(11)
a[(3<a) & (a<=8)]*-1

array([-4, -5, -6, -7, -8])

#### Extracting integer part of a random array using 5 different methods

In [23]:
Z = np.random.uniform(0, 10, 10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[7. 1. 2. 5. 7. 4. 4. 5. 9. 2.]
[7. 1. 2. 5. 7. 4. 4. 5. 9. 2.]
[7. 1. 2. 5. 7. 4. 4. 5. 9. 2.]
[7 1 2 5 7 4 4 5 9 2]
[7. 1. 2. 5. 7. 4. 4. 5. 9. 2.]


#### Create a 5* 5 matrix with values ranging from 0 to 4

In [24]:
a = np.zeros((5,5))
a = a+np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### Consider a generator function that generates 10 integers and use it to build an array

In [25]:
def generate():
        for x in range(10):
            yield x
Z = np.fromiter(generate(),dtype=float)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### Create a vector with size 10 ranging from 0 t 1 both excluded

In [26]:
a = np.linspace(0, 1, 12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Create a random vector and sort it

In [27]:
a = np.random.random(15)
a.sort()
a

array([0.04516181, 0.08210899, 0.10589874, 0.25584573, 0.2635573 ,
       0.32369637, 0.39835152, 0.47351186, 0.48088405, 0.50019123,
       0.51833315, 0.54532001, 0.67590912, 0.67914892, 0.75863349])

#### Adding elements of an array using 'reduce'

In [28]:
a = np.add.reduce(np.arange(4))
a

6

#### Checking two random arrays are equal or not

In [29]:
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)
print(np.allclose(a, b))
print(a, b)

False
[0 0 1 0 0] [1 1 0 0 0]


#### Making an array only readable

In [30]:
a = np.arange(10)
a.flags.writeable = False
a[1] = 4

ValueError: assignment destination is read-only

#### Conversion of cartesian to polar  coordinates

In [31]:
a = np.random.random((10, 2))
x, y = a[:, 0], a[:, 1]
R = np.sqrt(x**2+y**2)
T = np.arctan2(y, x)
print(R)
print(T)

[0.99052903 0.41946776 0.46401153 0.93121923 1.04375097 0.88885362
 1.02627252 0.53680538 1.3145026  0.89674964]
[1.51416707 0.65592447 1.15023167 1.48375323 0.41960091 1.56930153
 0.72140626 0.26124223 0.79164806 1.51975557]


#### Replacing max value with some other value

In [32]:
a = np.random.random(10)
a[a.argmax()]=8
a

array([0.16804011, 0.78038446, 0.6690736 , 0.71019498, 0.56939887,
       0.14650748, 0.12282077, 0.01309491, 0.43048046, 8.        ])

#### Printing all the elements of a numpy array

In [33]:
np.set_printoptions(threshold=np.inf)
a = np.zeros((25, 25))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

#### Converting float to int

In [37]:
a = np.arange(15, dtype=int)
a = a.astype(dtype = float, copy = False)

#### Equivalent of enumerate for numpy arrays

In [38]:
a = np.arange(10).reshape(5, 2)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])


(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(3, 0) 6
(3, 1) 7
(4, 0) 8
(4, 1) 9


#### Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [39]:
a = np.ones(10)
I = np.random.randint(0,len(a),20)
a += np.bincount(I, minlength=len(a))
print(a)

[2. 3. 2. 1. 5. 4. 2. 5. 2. 4.]


####  How to find the most frequent value in an array?

In [40]:
a = np.random.randint(0,10,10)
print(np.bincount(a).argmax())
print(a)

5
[5 7 7 5 5 6 7 6 3 9]


####  How to get the n largest values of an array?

In [41]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5

print (a[np.argsort(a)[-n:]])

[9995 9996 9997 9998 9999]


#### Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?

In [42]:
C = np.bincount([1,1,2])
A = np.repeat(np.arange(len(C)), C)
print(len(C))
print(A)

3
[1 1 2]


#### How to swap two rows of an array?

In [43]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [44]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
